version: '3.9'
services:
  # database section
  identitydb:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: identitydb
    environment:
      SA_PASSWORD: "Passw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - identity_sqlserver_data:/var/opt/mssql
    restart: always
    ports:
      - "1436:1433"
    
  microservices.idp:
    image: ${DOCKER_REGISTRY-}microservices
    build:
      context: .
      dockerfile: src/Microservices.IDP/Dockerfile

volumes:
  identity_sqlserver_data:
    external: false
      

